language: node_js
node_js:
    - "node"
install: true
script: echo "Skipping build"
deploy:
  edge: true
  provider: bluemixcloudfoundry
  skip_cleanup : true
  username: apikey
  password: -pwA-m5MmRgCTAVV1q0RyB1nSWuzGGjIW97x4DHc8VW-
  organization: aourarhikram3@gmail.com
  space: dev
  manifest: manifest.yml
  on:
     branch: master
  