language: node_js
node_js:
    - "node"
install: true
script: echo "Skipping build"
deploy:
  edge: true
  provider: bluemixcloudfoundry
  username: apikey
  organization: aou.ikram@gmail.com
  space: dev
  manifest: manifest.yml
  password:"-pwA-m5MmRgCTAVV1q0RyB1nSWuzGGjIW97x4DHc8VW-"