language: node_js
node_js:
    - "node"
install: true
script: echo "Skipping build"
deploy:
  edge: true
  provider: bluemixcloudfoundry
  skip_cleanup : true
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization : $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  manifest: manifest.yml
  on:
     branch: master
  