language: node_js
node_js:
    - "node"
install: true
script: echo "Skipping build"
deploy:
  edge: true
  provider: bluemixcloudfoundry
  skip_cleanup : true
  username: projectnode123@gmail.com
  password: Aourarh123@
  organization: projectnode123@gmail.com
  space: dev
  manifest: manifest.yml
  on:
     branch: master
  