language: node_js
node_js:
    - "node"
install: true
script: echo "Skipping build"
deploy:
  edge: true
  provider: bluemixcloudfoundry
  skip_cleanup : true
  username: apikey
  password: 2pEk-v-LF6TsMzGbofYm4OdcnDiNQmKo2m0nAARdzFsP
  
  manifest: manifest.yml
  on:
     branch: master
  